### ISSUE TITLE
Document advisor feedback in Airtable

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#10]
https://airtable.com/tblF8YI7ZkSVm1qwP/viwJt4QxAhT5NL6Wv?blocks=hide

**Comment by zspencer** [comment]
I may have some spoons available to do this; is there a link to where the feedback lives? The AirTable isn't accessible to me either; but if you gave me the headers I could give you a CSV.

**Comment by skullbunnygalaxy** [comment]
Thanks, @zspencer! I invited you to the AirTable. The feedback we're trying to document is given by artist advisors in the banchan-art channel in Discord.
