### ISSUE TITLE
Consistent Design across the site

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#114]
* [x] https://github.com/digitalworkersguild/banchan/issues/81
* [x] https://github.com/digitalworkersguild/banchan/issues/75
* [x] https://github.com/digitalworkersguild/banchan/issues/86
* [x] https://github.com/digitalworkersguild/banchan/issues/122
* [ ] Consistent header sizes (different pages use different header sizes/locations/styles right now?

**Comment by skullbunnygalaxy** [comment]
Closed and removed issues that are no longer applicable due to switch to DaisyUI.

**Comment by zkat** [comment]
Closing this as "too general"
