### ISSUE TITLE
Research options for analytics

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#139]
We've gone back and forth on if we want to have analytics or not. 
- Poorly implemented analytics can be worse than having no analytics. 
- We will want to be wary of what data is collected due to privacy concerns, including being cognizant of GDPR guidelines.

This issue is not for the actual implementation of analytics. This issue is to review: 
- what our options are if we are to pursue analytics
- pros versus cons of potential options
- if there are options that will provide useful data to artists that can be _implemented well_ while being considerate of the privacy of all end-users

**Comment by zkat** [comment]
this is done
