### ISSUE TITLE
Set up Apple/Google Pay for Web

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#186]

**Comment by zkat** [comment]
note: I think we don't need to do anything special here besides flip the flag in Stripe.

**Comment by skullbunnygalaxy** [comment]
Reminder to self: test the android side of this.

**Comment by zkat** [comment]
Update on Apple Pay: I've done what I believe is everything that needs to be done to enable it, including setting the Apple Pay Domain as per https://discord.com/channels/841573134531821608/1021668487824941086/1021669749182173264, but it still doesn't show up on Safari.

**Comment by zkat** [comment]
This looks like it's working, actually
