### ISSUE TITLE
Revisit/restyle core Form components

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#222]
This is particularly true for:

* [x] Select (needs search bar)
* [x] MultipleSelect (needs search bar and reordering based on selected elements)
* [x] MarkdownInput (try to hook up something like the [ToastUI WYSIWYG markdown editor](https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode))
* [x] The icons-next-to-inputs situation
* [ ] UploadInput (I think everywhere that uses it could do better, tbh)
* [x] Add Collapse component to work around #210

**Comment by rjt-rockx** [comment]
We can have icons displayed within the input containers as of right now, so we can mark that as done

**Comment by zkat** [comment]
I'm working on the Select component right now

**Comment by zkat** [comment]
UploadInput issue is here now: https://github.com/BanchanArt/banchan/issues/758
