### ISSUE TITLE
Firefox/Windows: circle filter around website logo scrolls with page sometimes

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#263]
You can kinda see it here, but the effect is much more jarring when you're scrolling because it's bouncing around violently:
![image](https://user-images.githubusercontent.com/17535/177049808-803222c2-9230-4245-84a1-d569978f8fb8.png)

I'm not really sure how to fix this, but it only happens on firefox so yolo

update: apparently also only a Windows issue?

**Comment by lodenrogue** [comment]
I'm trying to recreate this on my machine. What OS, version of Firefox, and which page are you seeing this on?

**Comment by zkat** [comment]
This is on Windows, latest Firefox, and I'm able to reproduce this on the user profile page and commission page pretty easily

**Comment by cyberglot** [comment]
I could not reproduce it on Mac. :(

**Comment by zkat** [comment]
> I could not reproduce it on Mac. :(

ugggh. Yeah, I can definitely still repro it on Windows. I'll narrow down the issue's scope, then. Thanks for taking a look.

**Comment by zkat** [comment]
this doesn't seem to happen anymore
