### ISSUE TITLE
Offering card drag image is entire webpage on Chrome and Edge

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#272]
When dragging an OfferingCard in the studio shop on Firefox, you (correctly), get a "ghost" image of the card getting dragged as the drag action happens.

On Chrome/Edge, on the other hand, the "ghost" image is _the entire webpage_.

I have no idea why this is happening, but it's horrible.

**Comment by VelvetteRld** [comment]
Did some reproduction attempt to have a reference (and checked if it was the correct scenario)

The issue looks less bad on Chrome and Edge than in the initial description in my tests but seems less bad at least.

All tests were done on a recent Windows 10 with 64 bit applications

Firefox 102.0.1 (with a bunch of extensions but should not matter, is the "correct" reference behavior) 
![banchan_272_firefox_102 0 1_64](https://user-images.githubusercontent.com/108237057/179817496-de98e1e7-fe98-4d7e-9f28-e224f8d98c0d.gif)

Edge 103.0.1264.62 no extension 
![banchan_272_edge_103 0 1264 62_64](https://user-images.githubusercontent.com/108237057/179817547-b3af2af5-e56b-45df-a08b-6b28a57e1fd0.gif)

Chrome 103.0.5060.114 no extension 
![banchan_272_chrome_103 0 5060 114_64](https://user-images.githubusercontent.com/108237057/179817602-03cffaa2-3ffb-41a2-a2de-17ba0aae01d7.gif)

**Comment by zkat** [comment]
this isn't happening anymore
