### ISSUE TITLE
Figure out how to distinguish dev/staging/prod

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#348]
A few things we use expect to only work on our actual, final live site, but not in dev, or in any future staging environment we might have. We need to figure out the best way to distinguish these environments and update those who might care:

* [ ] Sentry.io logging
* [ ] Plausible script

**Comment by bcgoss** [comment]
Sentry has two relevant configs. At app start we set the env to `config_env()` and Sentry will group events by env (see attached). Also, `included_environments` is a configures which envs where sentry should record, currently just `[:prod]`.

![Image](https://user-images.githubusercontent.com/8137732/186571666-f19aee95-be0a-4ddf-816d-656eb6eb8a76.png)

**Comment by zkat** [comment]
The issue is that all three return `:prod` for `config_env` (the term "dev" is a bit overloaded here--I'm referring to https://dev.banchan.art, which is still a "production" app, even if it's not THE production app). Reading through Sentry docs, I think I have an idea of how to do this, though, through an extra env var.
