### ISSUE TITLE
`Banchan.Offerings.Notifications.user_subscribed?` should check for studio subs, too

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#370]

**Comment by Jengamon** [comment]
Relevant code here, but where would I find studio subs? https://github.com/BanchanArt/banchan/blob/4617e82ba24ac29c2b18a3643aa5d1898aaa18e3/lib/banchan/offerings/notifications.ex#L20-L25

**Comment by zkat** [comment]
Here's the relevant code for studio subscriptions:

https://github.com/BanchanArt/banchan/blob/main/lib/banchan/studios/notifications.ex#L26

**Comment by zkat** [comment]
no, this is not actually a bug. We're already notifying people who are studio followers, which is what we want, and `user_subscribed?` is a specific check that's not even used right now.
