### ISSUE TITLE
Update new button from font element to SVG element

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#404]
From @LuxBrush:
> we should change the plus in the new button from a font element to an SVG element. Having it as a font-based element makes its position too inconsistent across browsers and operating systems. I noticed this today as I was using the website on Windows and my Chromebook.

Going to implement one of the font awesome icons for this with the `m-auto` class.

**Comment by zkat** [comment]
Closing this as we're moving all our icons to Lucide svg elements.
