### ISSUE TITLE
Auto formatting in text editor produces errors.

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#415]
When using the text editor, if you hit enter twice, it auto-adds `<br>`, which produces an error for disallowed HTML.

![image](https://user-images.githubusercontent.com/411004/192640106-7b712f35-289f-472c-a1ab-d4651b1d240c.png)

I suspect this will not be an issue once we replace ToastUI, but I am creating an issue in case it is something simple that can be resolved.

**Comment by zkat** [comment]
we no longer use MarkdownInput
