### ISSUE TITLE
When uploading multiple images to Works, removing an image does not work.

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#416]
1. When on your studio's portfolio page, select an image for upload. 
2. Then try to remove it. 
3. Select a different image for upload.

When you select another image for upload, it will re-add the removed image. Even if you remove the image again, it will upload the image anyways when you hit save.

**Comment by zkat** [comment]
Just more portfolio suckage. I think this is related to #633

**Comment by skullbunnygalaxy** [comment]
#633 closed due to new works feature, but this issue appears to be happening with the new works feature (#788). I was going to make a new issue but noticed this one hadn't been closed with 633. It seems like these are all the same issue.

Replication steps:

1. Create a new work.
2. Upload an image.
3. Hit X on image to remove it.
4. Upload new image.
5. Previous image that was removed will re-appear. This happens every time you add an additional image to the work.


Additionally, even if you remove the image before saving, the removed image still apears in the new work, which means the x button isn't really working on new uploads.

The image can be removed successfully when editing an already created work.
