### ISSUE TITLE
Text editor readibility issue 

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#479]
Issue: When switching to markdown within the Text Editor on the About page for a Studio, the text isn't visible on the dark theme. 
Details: Mac + Firefox
Image of issue:
<img width="521" alt="Screenshot 2023-07-13 at 6 20 37 PM" src="https://github.com/BanchanArt/banchan/assets/411004/afc4a0cd-0e83-4508-b210-ed9ae4de8b14">

**Comment by zkat** [comment]
I think this'll be fixed by #455 (which I'm mostly done with), so we maybe shouldn't test the textareas too much. This one is such garbage :(
