### ISSUE TITLE
Blank avatar displayed for Banchan when authenticating with Discord

### ISSUE THREAD

**Issue by rjt-rockx** [BanchanArt/banchan#481]
![image](https://github.com/BanchanArt/banchan/assets/10488070/744baaf2-3e35-445c-8f40-a2c14753ea25)

Should be a quick fix here since all that's needed is to upload the logo to the app at the Discord Developer dashboard. 
The app icon under the General Information tab needs to be updated as well as the one under the Bot tab too if the bot is being used.

**Comment by zkat** [comment]
Just fixed this. Should be good now. Thanks for spotting this!
![image](https://github.com/BanchanArt/banchan/assets/17535/4b9772c5-24d8-41ea-b15a-2e3599a8cf29)
