### ISSUE TITLE
Focus indicators are clipped on cards at low resolutions

### ISSUE THREAD

**Issue by rjt-rockx** [BanchanArt/banchan#482]
![image](https://github.com/BanchanArt/banchan/assets/10488070/ae45df60-1355-4a59-86bb-4c1c82daef8f)

When tabbing through elements at widths around 480px and lower, the focus indicators get clipped by the cards not having any padding between each other.

**Comment by zkat** [comment]
Moving this post-MVP because I don't think it's a beta blocker. Happy to take a patch to give them some padding, though. Or whatever needs done :)

**Comment by zkat** [comment]
This seems to be fixed, so I'm closing it: 

![Image](https://github.com/BanchanArt/banchan/assets/17535/583fa6cd-1fea-45bb-9cae-c674d0208c2b)
