### ISSUE TITLE
Portfolio Images Not Saving

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#484]
I tried to add new images to an existing portfolio. 
<img width="322" alt="Screenshot 2023-07-13 at 6 49 34 PM" src="https://github.com/BanchanArt/banchan/assets/411004/4bb287cc-576f-4341-b531-aecfc3c2d6b2">

However, after hitting save, the image reloaded as just the X:
<img width="674" alt="Screenshot 2023-07-13 at 6 49 47 PM" src="https://github.com/BanchanArt/banchan/assets/411004/e9e9cb43-f4d1-4d7c-a6ba-9328f9577ee4">

I did not see any error messages on the site itself. I did see the following errors in the Developer Tools after trying to add another image:
<img width="698" alt="Screenshot 2023-07-13 at 6 49 05 PM" src="https://github.com/BanchanArt/banchan/assets/411004/284185fe-f266-4684-96de-44c358832233">

Removing and trying to re-add the image results in the same issue.

**Comment by zkat** [comment]
Check in after a minute or so. This might be the thumbnailer job being slow.

**Comment by skullbunnygalaxy** [comment]
10+ minutes later, of the two pieces I added to the portfolio, one of the loaded, and the other is still just an X.

**Comment by zkat** [comment]
I can't repro this

**Comment by skullbunnygalaxy** [comment]
I'll test this again after clearing cache and all that.

**Comment by skullbunnygalaxy** [comment]
Confirmed this is not a cache issue. 

Replicated in Firefox Dev and Chrome Dev Browsers. 
The file is a jpg and only 917 kb.

Attaching file for replication.

![Image](https://github.com/BanchanArt/banchan/assets/411004/d59585f4-1e8e-46fe-a759-36c50e1a5547)

**Comment by skullbunnygalaxy** [comment]
After troubleshooting with Kat, we figured out that this is an issue with the dev server running out of memory when ImageMagick is trying to process thumbnails of the image in question. 

I was able to test and confirm this is not an issue on our prod server. I will add some useful notes to our wiki based on info that became relevant to troubleshooting this.
