### ISSUE TITLE
Search and filter options should not be displayed when there are no items to search through

### ISSUE THREAD

**Issue by rjt-rockx** [BanchanArt/banchan#492]
![image](https://github.com/BanchanArt/banchan/assets/10488070/2e11b3de-ea0b-4b2f-b7be-66b6fa982676)

**Comment by zkat** [comment]
I think I'm gonna close this: there's basically no scenario where this is gonna reasonably happen in production. It's only a thing that happens in local dev environments, and only temporarily until you fully set up a studio.
