### ISSUE TITLE
Google sign-in is not available

### ISSUE THREAD

**Issue by rjt-rockx** [BanchanArt/banchan#493]
According to #476, Google sign in is supposed to be available alongside Discord, but that's not present.

**Comment by zkat** [comment]
oops. We can't do Google sign in until we have an actual live site, because Google wants to actually see a real site in place before allowing it. I'll keep this open in the meantime.

**Comment by zkat** [comment]
closing in favor of https://github.com/BanchanArt/banchan/issues/226
