### ISSUE TITLE
Avatar and Profile background image not saving after upload 

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#494]
When editing my profile, I successfully uploaded an image for the background and the avatar, but it did not preview the images inside the modal. When my profile refreshed, I saw my text items and tags, but not the images. After 5 minutes I reloaded the page and I still don't see my images.

**Comment by kjrsten** [comment]
I tried again, using the Edit Profile interface and got the same result, no images

**Comment by zkat** [comment]
This is fixed.
