### ISSUE TITLE
Unable to create a studio with India and INR currency

### ISSUE THREAD

**Issue by rjt-rockx** [BanchanArt/banchan#495]
![image](https://github.com/BanchanArt/banchan/assets/10488070/bac7ea3d-49e9-4cd3-ae96-4d66a43d3762)

Clicking on the Save button doesn't throw an error but just resets the form instead, which is kinda annoying.

**Comment by zkat** [comment]
from the logs:

```
Got: {:error, #Ecto.Changeset<action: :insert, changes: %{handle: "rjt-studio", name: "rjt studio", country: :IN, default_currency: :INR, about: "making a studio", mature: true, payment_currencies: [:USD]}, errors: [default_currency: {"Must be one of the selected payment currencies.", []}], data: #Banchan.Studios.Studio<>, valid?: false>}
```

tl;dr this should be validating earlier, but for some reason is allowing submission to happen? Weird.
