### ISSUE TITLE
Gallery images enlarged if they are smaller than the gallery thumbnail size

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#497]
Minor issue:

If the finished artwork is smaller than the gallery thumbnail, it is blown up to compensate, causing a blurry effect (example: pixel art avatars that are small)

Possible solution: Do not enlarge to fit if the final image is smaller than N x N pixels. Center the image instead? It might be hard to make this look good.

Aside: I don't know how to add a label to an issue in Github, clicking on labels in the right column isn't doing it.

<img width="1013" alt="Screen Shot 2023-07-13 at 6 39 37 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/3e9a2381-6f25-4c99-9e1b-be80eda54d25">

**Comment by rjt-rockx** [comment]
This is a scaling issue, iirc there's different algorithms to rescale pixel art without causing fidelity loss. 

https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms is worth referencing.

**Comment by zkat** [comment]
Specifically, this is an issue with the Thumbnailer, which calls out to imagemagick. Getting a good imagemagick incantation that works in the general case is pretty hard, afaict, but I think we can make it a bit smarter than it is right now. I could definitely use some help from someone with more experience using it/processing images in general, though. That code is here: https://github.com/BanchanArt/banchan/blob/27ae4cdcae26b49bebeb9c16a6ee71f6bcba73ca/lib/banchan/workers/thumbnailer.ex#L116-L154

**Comment by zkat** [comment]
Moving this post-MVP/beta because while it's definitely an issue, I don't think it warrants blocking beta release.

**Comment by zkat** [comment]
This might "magically" be fixed by #610, so I'm moving it to this sprint just to see if that's all that's needed.

**Comment by zkat** [comment]
This is partially fixed as of #784, but now we need to go through the site and make sure that:

1. We don't upscale images when we display them
2. Places that were used to upscaled images don't break (like cards, which are definitely broken now).

Moving this back to the backlog and reassigning, since this is now frontend work.

**Comment by zkat** [comment]
This is fixed in #788, along with the larger portfolio redesign.
