### ISSUE TITLE
UX Question: Why is the About section in a card under "Shop"?

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#498]
It's confusing to me to see a card labeled "about" under the "Shop" tab. It is functional, it does take me to the "about" for the artist, I'm just not sure why it's previewed here.

<img width="1277" alt="Screen Shot 2023-07-13 at 6 48 41 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/6d059644-9c39-41d8-9bee-96e21b5bc9a4">

**Comment by rjt-rockx** [comment]
Ideally it'd be a short description under the name, and a longer description under the About tab.

**Comment by zkat** [comment]
Yeah this could definitely use a better design. I just didn't want to completely bury the About in a separate tab

**Comment by kjrsten** [comment]
If the text is limited to <500 words or so, I would surface it at the top level if possible 
<img width="1350" alt="Screen Shot 2023-07-13 at 6 55 41 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/bb5af57e-d6c5-4fc4-baf1-dadc2040e30e">

**Comment by kjrsten** [comment]
I can understand wanting to have it out there, the "about" tab itself is pretty unobtrusive and I might never click it.

**Comment by kjrsten** [comment]
But shop items should not be hidden, therefore landing on "Shop" to begin with is the right choice
