### ISSUE TITLE
Unable to add Profile and Header image on individual artist profile

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#508]
I successfully added images to my Studio identity, but I am still trying and failing to get my personal avatar and cover image to stick.

<img width="918" alt="Screen Shot 2023-07-14 at 5 48 59 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/5b95c46f-1250-44bb-85e5-42e6a84cfdd2">

**Comment by kjrsten** [comment]
Closing this as a duplicate!

**Comment by zkat** [comment]
wait I just fixed this where's the dupe?

**Comment by kjrsten** [comment]
I can't find it now~ I can confirm this works though!
