### ISSUE TITLE
Changing status of incoming Commission needs more call to action - UX issue

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#511]
When I look at another artist's work, this button is inactive, I cannot change it (even though there is a "caret >" indicating a possible dropdown.

When I look at my OWN work that has been requested, I DO need to change this status by using this button (currently says "submitted" in the screenshot), but it is gray and quiet. 

Ideas:

- Make it green?
- Add prominent call to action as being the next step/a step artists must do

<img width="658" alt="Screen Shot 2023-07-14 at 5 59 32 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/fe2d3060-e5ed-452f-9649-3f4b5d8921d1">

**Comment by kjrsten** [comment]
TBH I feel that this whole section needs more importance/highlighting 

<img width="1281" alt="Screen Shot 2023-07-14 at 6 17 41 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/ca452a66-4899-4dbe-b297-73928f9ed2eb">

**Comment by zkat** [comment]
Makes sense. For the record, that area is called the `StatusBox`

**Comment by zkat** [comment]
I could really use some help designing the `StatusBox` in a better way. I've iterated on it a lot, and it's clearly not quite there yet, but it's a very important part of the commission flow. I'm willing to block the beta on this, if needed.

**Comment by kjrsten** [comment]
I have a few ideas, I'll noodle on it

**Comment by zkat** [comment]
For the sake of clarifying just how muchḣheavy lifting this thing does: the statusbox is the control for a state machine that cycles between various states:

* Submitted (initial state)
* Accepted (studio has decided to work on the commission. Needed before you can invoice)
* Rejected (studio has turned down the commission. Any deposits will be refunded)
* In Progress (studio is actively working on it)
* Paused (studio is temporarily pausing work on it)
* Waiting (studio is waiting for the client to respond with something)
* Withdrawn (the _client_ has withdrawn the commission. Any deposits will be refunded)
* Accepted (the client has paid the final invoice, and the commission is closed)

Once accepted, the _studio_ can move freely between `In Progress`/`Paused`/`Waiting`, and will always be able to go to `Rejected`, even after initially accepting.

When a client has `Withdrawn` a commission, they can only resubmit it by setting the status to `Submitted`.

When a studio has `Rejected` a commission, they can move it back to `Accepted` and start over.

`Accepted` is a final state.

**Comment by kjrsten** [comment]
This all makes sense, thanks!

**Comment by kjrsten** [comment]
I may have attached this screenshot to another ticket? But here are my ideas for the status box

![banchan2](https://github.com/BanchanArt/banchan/assets/5471856/cdeb91b0-884e-4d9d-99f3-9a71d0c448db)
