### ISSUE TITLE
I was allowed to create an Offering without terms

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#518]
I just created an offering "One Crow Outline" without specifying terms, I thought that was a required step. I did not un-collapse the "Terms" item in the creation form.

**Comment by zkat** [comment]
Terms are optional, but I think the experience could be improved: for example, you shouldn't be required to agree to the terms if the offering doesn't have terms set up.

In an ideal world, everyone would have terms, but in reality, a lot of amateur artists probably don't have the understanding or resources to confidently craft their own, and might not want to be forced to.

An alternative might be to have site-wide default terms that studios can then override. 

Not sure which is the best
