### ISSUE TITLE
Video thumbnails keep pulsating for clients, even after thumbnail generated and page refreshed

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#520]
uploads also immediately 404 when requested after creation

I think media uploads might just need a bit more attention and love. 

This might be related to #484

**Comment by skullbunnygalaxy** [comment]
I could not replicate this issue. However, I used a very small .mov video that is only 2 seconds and 1.6 MB. It might be best to re-try with the file that cause the issue when observed before.

The behavior I saw was a pulsing broken thumbnail after upload, but it still allowed me to download the video successfully. I did have to refresh the page in order for it to update the broken thumbnail and pulse to a non-pulsing thumbnail.

**Comment by zkat** [comment]
Closing this in favor of #584
