### ISSUE TITLE
Text editor controls are white (invisible in Light Mode) plus script warning on Quotes

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#525]
I saw that there may be a new text editor, tried it out in the Offering comments area -- see GIF.

The text controls appeared invisible until rolled-over in the LIGHT interface, because they are white

"script warning" appeared when the "quote" button is used

The message text is populated back into the text entry field after the comment is posted
![new-rich-text](https://github.com/BanchanArt/banchan/assets/5471856/61e5d69f-c542-4e1c-8a2b-f461aa33dd80)

<img width="825" alt="Screen Shot 2023-07-16 at 10 02 32 PM" src="https://github.com/BanchanArt/banchan/assets/5471856/e3f98c97-75ec-4cf8-b6dc-20e0cdf7c1a9">

**Comment by zkat** [comment]
Fixed the icons. Created https://github.com/BanchanArt/banchan/issues/528 for the script validation thing
