### ISSUE TITLE
Fix styling of offering and studio lists

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#560]
I feel like they're too tightly packed right now.

From the Discover/Home pages: 

![Image](https://user-images.githubusercontent.com/17535/258658250-ffb0e312-878c-4751-a22d-e43d3b70c42e.png)

From the Studio Shop page: 

![Image](https://user-images.githubusercontent.com/17535/258658271-7330606d-cfcd-4865-a55c-15f12d584309.png)

**Comment by rjt-rockx** [comment]
the new offering button shouldn't look like a placeholder card either, could be a more explicit floating button instead
