### ISSUE TITLE
Freshen up studio card design

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#561]
and maybe stop making them zoom on hover

**Comment by rjt-rockx** [comment]
scale on hover isn't too bad, but yeah it can feel off
![image](https://github.com/BanchanArt/banchan/assets/10488070/5f7025a3-a416-4b55-b57c-9f65b8895133)
reference mockup

**Comment by rjt-rockx** [comment]
card chrome could be removed to make it consistent with the other cards on the site too
