### ISSUE TITLE
Fix tab centering/width on studio page

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#562]
The shop/portfolio tabs should be centered and width-limited, but they're slammed to the left right now.

See:

![Image](https://user-images.githubusercontent.com/17535/258658376-113c53a3-9dc7-4114-acdf-1185f1e21416.png)

**Comment by rjt-rockx** [comment]
could probably use icons for each tab too, along with a bit more vertical padding so that they're more tappable on mobile
