### ISSUE TITLE
Slots break when editing their amount after accepting a commission

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#575]
When editing slots in an existing offering, there are two scenarios where it breaks. I am including both in this ticket as they are likely related. 

Note: this is not taking into consideration the proposal number due to that appearing to be broken once slots are filled. I will open a separate ticket and link it below for that issue.

## First way
1. Create an offering with more than 1 slot. Example: 3/3.
2. Accept a proposal, which turns it into a commission and therefore takes up a slot. Example: 2/3. 
3. Edit the existing offering to have only 1 slot. Example: 0/1.
4. Check the page for the ability to request a new commission. 
Result: The "Request" button is still there instead of the expected "Notify me" button, which is what currently shows on offerings that started with one slot and had it filled. 
Clicking on the Request button takes you to the "Request a Commission" page. After filling in the required details and hitting submit, instead of creating the proposal, it redirects you to the store page, which may lead clients to think they have submitted a proposal due to a lack of a message of any kind. 

## Second way
1. Create an offering with 1 slot, Example: 1/1.
2. Accept a proposal, which turns it into a commission and therefore takes up a slot. Example: 0/1.
3. Edit the existing offering to have more than one slot. Expected behavior: 3/4. What actually happens: 0/4.
4. Check the page for the ability to request a new commission. 
Result: Since the slot still shows 0, it will not allow a client to put in a new commission and instead shows the "Notify me" button.

**Comment by skullbunnygalaxy** [comment]
For the second issue, I realized the issue was that it had closed the commission previously, which I did not notice when adjusting the slots. This is related to #574. I recommend making the open and close state of accepting proposals more clear in the area where slots and proposals are adjusted.  It may help to move it under the slot and proposal settings. 

This means the only issue remaining with that is it is not taking into consideration the max proposal number, which has a separate issue #576.

However, the first issue still exists. I checked, and it shows as open, allows filling out the proposal form, and then doesn't create it. This is also likely more related to #576 than I initially realized.

**Comment by zkat** [comment]
the reason the redirect looked like it didn't do anything is because I was doing flashes wrong, and the error message wasn't showing up. That has been fixed. I'm keeping this issue open for the sake of adding an available slots check to the offering edit endpoint, so it closes an offering if you reduce its slot count below available.
