### ISSUE TITLE
Max Proposals appears to not work when Slots are filled.

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#576]
We have the following explanation above the section for setting Max Proposals and Slots.
> Accepted commissions do not count towards your Max Proposals, and proposed commissions do not count towards your Slots.

However, when slots get filled, proposals can no longer be made. This was discovered while testing #575.

**Comment by zkat** [comment]
What's happening is that when slots get filled, the offering is closed. Regardless of your proposal settings, you can't try to send a proposal to closed offering. Therefore, this is working as intended.
