### ISSUE TITLE
Rename "Report a Bug" to "Send Feedback"

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#585]
It would be good to repurpose the current bug reporting code to let folks give regular product feedback, rather than just reporting bugs

**Comment by skullbunnygalaxy** [comment]
- [ ] Adding a select dropdown between bugs and feedback to the form. 
- [ ] Adjusting the API to apply the relevant tag based on which is selected.
- [ ] Adjusting wording to include bugs and feedback.

**Comment by skullbunnygalaxy** [comment]
This is now completed with #593.
