### ISSUE TITLE
User profile page weirdness with ellipse menu

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#586]
Immediately after visiting any user profile page, this is what it looks like, with the layout all over the place and the menu stuck open (it can't be closed):

![image](https://github.com/BanchanArt/banchan/assets/17535/4b5ccecd-2b4a-4b6c-9065-266ad39a32b0)

**Comment by skullbunnygalaxy** [comment]
I was able to replicate this on my Pixel 6 in Chrome.
