### ISSUE TITLE
Disallow sub-$20 offerings but make Inquire special

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#605]
Only two scenarios are valid:

1. You have enough default options to add up to $20 or more
2. You have *no options defined at all*, in which case your commission is "Inquire"

**Comment by skullbunnygalaxy** [comment]
I keep thinking about the idea of requiring some amount to be applied by the studio before accepting the inquire option. Even if the studio is doing things hourly, ideally they should require a deposit for either the first hour or an estimated portion of the minimum estimated hours they expect the commission to take.

**Comment by zkat** [comment]
update: gonna disable sub-$20 altogether for now
