### ISSUE TITLE
Can't seem to add an ADD ON

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#608]
I don't see a way to add the $5 add-on for this item.

![Screen Shot 2023-08-12 at 4 17 36 PM](https://github.com/BanchanArt/banchan/assets/5471856/5fb9bf6d-42c9-44c7-aab3-66c5b1d8f74a)

**Comment by zkat** [comment]
this was a hiccup because I briefly broke it, but the fix has been pushed by now.

![Image](https://github.com/BanchanArt/banchan/assets/17535/36e26df8-9185-4286-91bf-216d4b28fd3c)
