### ISSUE TITLE
As an Artist, adding an Option should expand the form

### ISSUE THREAD

**Issue by kjrsten** [BanchanArt/banchan#609]
When I tried to add an option to one of my old items, the line item appears collapsed. It would be nice to have this expanded by default upon click of "Add Option" (see gif)
![addoption](https://github.com/BanchanArt/banchan/assets/5471856/5655bf93-4d57-44bb-8095-5362cb648b92)

**Comment by kjrsten** [comment]
Important note: None of these changes saved to my item. When I navigate back to it, the old options are still there.

This item was created a few weeks ago, and I used the "three dots" button next to the "Request" button to "EDIT" and add different options.

I also was unable to change it from using AUD$ to USD$

**Comment by zkat** [comment]
As far as the inability to update goes: are you still seeing it? I tried editing that exact offering myself, including changing currencies, and it worked just fine: 

![Image](https://github.com/BanchanArt/banchan/assets/17535/20e5de85-cfbf-4138-b32b-54a2cb8befd7)

**Comment by zkat** [comment]
The bug here is resolved so I'm turning this into an enhancement as far as auto-opening new offerings goes

**Comment by rjt-rockx** [comment]
This probably relates to a broader issue of being able to set the default open state of a Collapse component.
