### ISSUE TITLE
Set up Freshdesk

### ISSUE THREAD

**Issue by skullbunnygalaxy** [BanchanArt/banchan#615]
Set up Freshdesk: https://www.freshworks.com/freshdesk/

This allows us to:
- ability to pull in reports from social media
- knowledge base 
- letting people interact with us without having to make a github account 
- instead of everything being thrown into github issues, we'll be able to sort tickets on freshdesk to see which would be most relevant for posting to github

**Comment by skullbunnygalaxy** [comment]
- [ ] Set up custom domain: https://support.freshdesk.com/en/support/solutions/articles/37590
- [ ] Connect to social media
- [ ] Set up knowledge base
- [ ] Set up templates based on feedback vs bugs
- [ ] Update theme to match our website

**Comment by zkat** [comment]
I'm going to take care of updating our site links to point to help.banchan.art
