### ISSUE TITLE
On mobile, cannot scroll unless touching certain elements.

### ISSUE THREAD

**Issue by LuxBrush** [BanchanArt/banchan#676]
When viewed on a mobile device, or in dev mode view as mobile, you cannot scroll unless you are touching or hovering over certain elements.
I also noticed that you can't tap/click on certain elements as well.
Here's a link to a video demonstrating it.
[https://drive.google.com/file/d/1tijlpWfhwmHOcwwD3f4A_5sSQodHda8V/view](https://drive.google.com/file/d/1tijlpWfhwmHOcwwD3f4A_5sSQodHda8V/view)

**Comment by rjt-rockx** [comment]
Could you share device and browser details please :o
Also, does this happen the same way on other browsers too?

**Comment by LuxBrush** [comment]
Thanks, I forgot to say this was on Firefox on both desktop and mobile. And mobile was on a Pixel 7 Pro running Android 13.

**Comment by LuxBrush** [comment]
Also, I can confirm it's happening on Edge and Chrome. Just tested it.

**Comment by LuxBrush** [comment]
After some more testing, it seems the bug is only on Windows, ChromeOS, and Android. I was not able to duplicate the bug on my iPad in any browser.
