### ISSUE TITLE
Commission Gallery Images do not display in sorted order on public display

### ISSUE THREAD

**Issue by Jackalune** [BanchanArt/banchan#691]
**Issue:** Gallery images display in incorrect order on `https://banchan.art/studios/foo/offerings/bar` but do display in correct sorted order on `https://banchan.art/studios/foo/offerings/bar/edit`

Open/Hidden/etc statuses do not seem to affect this.

**Example:**
Edit page (correct order I sorted images into): 
![image](https://github.com/BanchanArt/banchan/assets/25205877/7231b0cb-869f-498a-8302-974dc4578664)

Public/view page (incorrect order): 
![image](https://github.com/BanchanArt/banchan/assets/25205877/a2dbe672-6072-48e2-a20f-a9439156a576)

I'm able to recreate this on two separate commission offerings, one with 2 gallery images, and one with 3.

Steps to Reproduce:
- Upload more than one image to the "Gallery Images" option on commission creation.
- Drag and drop to reorder them.
- Click save.
- The images will display correctly in the edit page, but will not change order on the public page.

**Comment by zkat** [comment]
Obsolete: galleries have been replaced by Works. There's no longer full sort support, but you can opt to "feature" a Work to have it show up at the top of the list.
