### ISSUE TITLE
Message remains in the input box after it's been sent in Commission discussion

### ISSUE THREAD

**Issue by TheWeezyOfOz** [BanchanArt/banchan#730]
![image](https://github.com/BanchanArt/banchan/assets/24808598/44bf9829-f907-4929-8032-750e26465b2c)

In the commission discussion, the message remains in the input box after it's been sent. This doesn't seem to happen every time.

For context, I'm using Firefox.

**Comment by zkat** [comment]
A fix for this has been deployed
