### ISSUE TITLE
The Save button stays disabled on the 'Edit Offering' page after a new option is added and then removed.

### ISSUE THREAD

**Issue by LuxBrush** [BanchanArt/banchan#736]
I found a bug with the save button on the 'Edit Offering' page.
If you add an option and then remove it without filling it out, the save button on the page stays disabled, so if you've made other changes, you now cannot save them.
I've included a link to a video demonstrating the bug in action.
[save_disabled_bug.mp4](https://drive.google.com/file/d/11QBNWs6cgGLbusgBqcNXiakjJo9Bhq76/view)

**Comment by zkat** [comment]
This... looks like it might be an honest-to-goodness bug with Ecto, which is _very_ frustrating. I'm pretty sure I'm doing everything right here. I've asked on the slack for help, and I may have to post on the elixir forums, because this is really ridiculous.
