### ISSUE TITLE
Mature artworks appear in Discover page when setting is unchecked

### ISSUE THREAD

**Issue by FeroTheFox** [BanchanArt/banchan#754]
This only happens on the initial load of the page. After the refresh with the alert toast, mature artworks are hidden. Also works as intended on subsequent refreshes

**Comment by rjt-rockx** [comment]
canrepro, could still see the mature offerings after refreshes though

**Comment by zkat** [comment]
The reason for not seeing them after refreshes is probably that they're paged out at that point. 

Anyway I'm pretty sure I know how to fix it and I'll tackle it next. I think I got a bit too clever with my sql
