### ISSUE TITLE
Can't login with Firefox unless Tracking Protection is turned off

### ISSUE THREAD

**Issue by NoraCodes** [BanchanArt/banchan#775]
Firefox includes a feature called Tracking Protection, which is on by default. When attempting to log in to Banchan without disabling Tracking Protection, the Log In button remains disabled (grey) and login is impossible. Turning Tracking Protection off (adding an exception for https://banchan.art) allows login to work.

The following message is shown in the browser console whether or not Tracking Protection is on.

```
Content-Security-Policy: The page’s settings blocked the loading of a resource at blob:https://banchan.art/97c8622c-f166-4dfc-a647-0549eb9c51a1 (“default-src”).
```

This message repeats 8 times. The UUID differs.

**Comment by skullbunnygalaxy** [comment]
I am able to login with Tracking Protection on in Firefox, but we may have different settings. Would you please let us know what specific settings you are using within Tracking Protection?

For context, here is how I have mine set up:
<img width="667" alt="Screenshot of Firefox tracking settings" src="https://github.com/BanchanArt/banchan/assets/411004/086a81e0-be04-4b40-91fd-0cc43f3b0ec1">

**Comment by zkat** [comment]
I fixed something related to this. Do you mind giving it another chat, @NoraCodes?

**Comment by NoraCodes** [comment]
Apologies for missing the message - yes, it works for me now, thank you so much!

**Comment by zkat** [comment]
Awesome. Thanks for checking! Closing this out, then :)
