### ISSUE TITLE
Options non-existent, saving goes to a "not found" page, cannot go far with creating a studio either

### ISSUE THREAD

**Issue by therealNAAN** [BanchanArt/banchan#779]
Hello! Sorry for the very long subject title, I just wanted to be specific before writing my issues below ^^;

A few months ago, I was accepted to BanchanArt and...immediately found many issues that I don't see anyone else have? I tried to look through the github before posting this, and I couldn't find anyone talking about these problems. ([Anything similar is here](https://github.com/BanchanArt/banchan/issues/736), but at least that person presumably has been able to use most of their account!) At the time I thought, maybe it's just site hiccups. Today I uh remembered I had an account, so I took a look again a few minutes ago--and nope. Still have the same issues as I did a few months ago.

First, my profile page--I think I was only able to write and save a description by sheer luck, because uploading a header page and saving gets me a 404, same as for the profile picture. I also keep trying to save my interests, and they keep disappearing because, you guessed it, the 404 page. (Really, it's just a blank page that says "Not found" in Times New Roman) There is also no space to write the links and social media on my end?

![image](https://github.com/BanchanArt/banchan/assets/94943717/efb62909-3e34-4994-ab89-815c79c14545)
![image](https://github.com/BanchanArt/banchan/assets/94943717/d75a93b6-e29a-408c-82fe-2dc6e509ad87)

Second--when it comes to the "create a new studio" option, I have the same issue. In fact, worse, because the save button is greyed out--on top of having no option to add a country and default currency.

![image](https://github.com/BanchanArt/banchan/assets/94943717/67b99872-79c2-4abe-9bef-69ac9b5b3d49)

The only place I can safely edit and save as normal is in my settings ^^; I would liked to have been able to use this site, so I hope there's a solution to all of this?

**Additional details:** I am on Windows 11, using Firefox. I verified my account already months ago when I got the confirmation email as well.

**Comment by skullbunnygalaxy** [comment]
Which version of Firefox are you using? Also would you please provide a list of any add-ons that you have enabled on Firefox?

**Comment by therealNAAN** [comment]
According to my browser, I am on Version 122.0 (64 bit).

Here are my active add-ons:
AdNauseam
Archive Page
Auto Tab Discard
Blocktube
Bypass Paywalls Clean
Clear Cache
ClearUrls
Comment Wizard (for Webtoons)
Consent-O-Matic
Control Panel for Twitter
Don't Accept image/webp
Don't track me Google
DuckDuckGo Privacy Essentials
Enhancer for Youtube
FicLab
Graze
IDM Integration Module
LeechBlock NG
New XKit
OneTab
Save webP as PNG or JEPG
Share to Mastodon
Sponsorblock
StreetPass for Mastodon
Tab Session Manager
Tab Stash
Tampermonkey
TrackMeNot
TTV LOL PRO
uBlock Origin
WhatCampaign
XKit Rewritten

**Comment by skullbunnygalaxy** [comment]
Thanks for your response! I discussed this with @zkat who mentioned it may be related to an error tied to the rich text editor that has been reported sporadically. 

Are you familiar with using Developer Tools? If you have Dev Tools open to the Network Tab before going to one of the pages where it fails and then navigate to that page, it should show you any errors. If you provide us with the information in that error message, then we can confirm if it is the same issue or a separate one.

**Comment by zkat** [comment]
This should be fixed now! It was indeed That One Bug. Please lmk if you run into anything else--this was a major thing causing all sorts of problems around the site, sporadically, but it should be good now :)

**Comment by therealNAAN** [comment]
Hello! I got a little busy all of a sudden, so I completely overlooked this, sorry--receiving the last message in my email box reminded me! Not sure why it was closed, despite not having done the thing? ^^;  (Though it was my bad for having forgotten.)

While editing my profile page now works:

![image](https://github.com/BanchanArt/banchan/assets/94943717/e2c7fa34-35fd-457c-b5c0-55d1e930de17)
![image](https://github.com/BanchanArt/banchan/assets/94943717/b3257ead-2ac7-40cb-a7ab-f8673fa19c17)

(Hurray!)

--the Studio page is still super buggy. I had to zoom out to show what I mean:

![image](https://github.com/BanchanArt/banchan/assets/94943717/cf91b494-952d-4372-9577-ddf7070011c4)

When I log in normally:
![image](https://github.com/BanchanArt/banchan/assets/94943717/84fa21ed-90c9-4a21-9b0d-94da77aceb8d)

When I zoom out and scroll up, it refuses to let me reach the top. I have to put the page at 100% again to be able to show you how it looks now.

I performed the Network Tab suggestion on the page and received this:
![blocked](https://github.com/BanchanArt/banchan/assets/94943717/c787840f-ea27-41c3-8054-ead568e846e6)

Only thing I found related to the "plausible outbound links" [was this](https://plausible.io/docs/outbound-link-click-tracking), but well, maybe you will tell me what's that about with regards to Banchan xD;;

**Comment by zkat** [comment]
Yeah I ran into this one. The fix should be published now. The "plausible" thing shouldn't be a problem: that's just our analytics tracker getting blocked by your browser.

We do cookie-less, basic analytics mostly to get a sense of site visits and where people are going, and we don't otherwise collect any kind of invasive or personal data.

Anyway give it a shot now, it should be good!

**Comment by therealNAAN** [comment]
Yep, works great now! Hopefully no more issues arrive ^^; Thank you so much for all the help and hard work!
