### ISSUE TITLE
cache-busted static assets are getting committed to repo

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#88]
I'm not really sure how this is _meant_ to work, based on what I saw from a stock Phoenix app, but it looks like we're committing stuff like `/priv/assets/robots.txt-deadbeefbadc0ffee`. Would be nice to figure this out.

This seems like a good first contribution for those interested.

**Comment by tacohole** [comment]
Okay I've spent a bit trying to conclusively determine how these got here/how to reproduce:
1. Files didn't exist before [this commit](https://github.com/digitalworkersguild/banchan/commit/3cae3d02a3d94d7b273d34e5f9a39459b33db3d4). 
2. Removing the files (or modifying them to encourage a re-hash) and re-building the project does *not* rebuild the files
3. The JS framework does not appear to be actively utilizing the hashed versions; replacing `favicon.ico` with another file results in the unhashed version displaying:
<img width="250" alt="Screen Shot 2022-02-06 at 1 57 51 PM" src="https://user-images.githubusercontent.com/27251346/152697285-5ea3f7f2-de7f-4b67-984c-caf92150d61b.png">

 All this leads me to believe that a build was performed at some point in the process of that commit when the config was something different than what we find [here](https://github.com/digitalworkersguild/banchan/blob/04c9f2fd5464e697d9b69e4bc524ace5f6487487/config/config.exs#L50), and that these files can simply be deleted without worrying that they'll pop back up.

Happy to file a PR for this or discuss further/handle some other way!

**Comment by zkat** [comment]
1. That is correct, this started happening as part of the overhaul of static assets
2. You need to do `mix phx.digest` to generate them, iirc
3. Javascript and CSS are handled separately from this. And the favicon isn't served through JS at all.

You're right that a build was performed... I guess the challenge with this issue is figuring out how to set up either the build or the ignores such that these cache-busted assets aren't a nuisance?

**Comment by tacohole** [comment]
Okay cool! Thanks for explaining. This [blog post](https://nobilisdata.com/blog/one-way-to-handle-static-files-in-phoenix-1-6/) seems to offer a solution that worked well when I tested locally; the only hang-up is that we'd also need to re-home `priv/static/images` in order to ignore all of `priv/static`. Does it make more sense to move these to `priv/images`, or up to `assets`?
